// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (sku, name, description, low_stock_threshold)
VALUES ($1, $2, $3, $4)
RETURNING id, sku, name, description, low_stock_threshold, created_at
`

type CreateItemParams struct {
	Sku               string
	Name              string
	Description       string
	LowStockThreshold int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.LowStockThreshold,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.LowStockThreshold,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, sku, name, description, low_stock_threshold, created_at FROM items
ORDER BY created_at
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.LowStockThreshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemFromID = `-- name: GetItemFromID :one
SELECT id, sku, name, description, low_stock_threshold, created_at FROM items
WHERE id = $1
`

func (q *Queries) GetItemFromID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemFromID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.LowStockThreshold,
		&i.CreatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET sku = $2, name = $3, description = $4
WHERE id = $1
RETURNING id, sku, name, description, low_stock_threshold, created_at
`

type UpdateItemParams struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	Description string
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.LowStockThreshold,
		&i.CreatedAt,
	)
	return i, err
}
