// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, is_active
`

type CreateLocationParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation, arg.Name, arg.Description)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
UPDATE locations
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, id)
	return err
}

const getAllLocations = `-- name: GetAllLocations :many
SELECT id, name, description, created_at, is_active FROM locations
WHERE is_active = true
ORDER BY created_at
`

func (q *Queries) GetAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationFromID = `-- name: GetLocationFromID :one
SELECT id, name, description, created_at, is_active FROM locations
WHERE id = $1
`

func (q *Queries) GetLocationFromID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationFromID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description, created_at, is_active
`

type UpdateLocationParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation, arg.ID, arg.Name, arg.Description)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}
