// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID                uuid.UUID
	Sku               string
	Name              string
	Description       string
	LowStockThreshold int32
	CreatedAt         time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	Role           string
	CreatedAt      time.Time
}
