// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID                uuid.UUID
	Sku               string
	Name              string
	Description       string
	LowStockThreshold int32
	CreatedAt         time.Time
	IsActive          bool
}

type Location struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Stock struct {
	ID         uuid.UUID
	ItemID     uuid.UUID
	LocationID uuid.UUID
	Quantity   int32
}

type StockMovement struct {
	ID             uuid.UUID
	ItemID         uuid.UUID
	FromLocationID uuid.NullUUID
	ToLocationID   uuid.NullUUID
	Quantity       int32
	MovedBy        uuid.UUID
	MovedAt        time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
