// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllStockWithThreshold = `-- name: GetAllStockWithThreshold :many
SELECT s.id, s.item_id, s.location_id, s.quantity, i.name, i.sku, i.low_stock_threshold
FROM stock s
JOIN items i ON s.item_id = i.id
ORDER BY s.location_id
`

type GetAllStockWithThresholdRow struct {
	ID                uuid.UUID
	ItemID            uuid.UUID
	LocationID        uuid.UUID
	Quantity          int32
	Name              string
	Sku               string
	LowStockThreshold int32
}

func (q *Queries) GetAllStockWithThreshold(ctx context.Context) ([]GetAllStockWithThresholdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStockWithThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStockWithThresholdRow
	for rows.Next() {
		var i GetAllStockWithThresholdRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
			&i.Name,
			&i.Sku,
			&i.LowStockThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowStockItems = `-- name: GetLowStockItems :many
SELECT s.id, s.item_id, s.location_id, s.quantity, i.name, i.sku, i.low_stock_threshold
FROM stock s
JOIN items i ON s.item_id = i.id
WHERE s.quantity < i.low_stock_threshold
AND i.low_stock_threshold > 0
`

type GetLowStockItemsRow struct {
	ID                uuid.UUID
	ItemID            uuid.UUID
	LocationID        uuid.UUID
	Quantity          int32
	Name              string
	Sku               string
	LowStockThreshold int32
}

func (q *Queries) GetLowStockItems(ctx context.Context) ([]GetLowStockItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLowStockItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLowStockItemsRow
	for rows.Next() {
		var i GetLowStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
			&i.Name,
			&i.Sku,
			&i.LowStockThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockForItemAllLocations = `-- name: GetStockForItemAllLocations :many
SELECT id, item_id, location_id, quantity FROM stock
WHERE item_id =
$1
`

func (q *Queries) GetStockForItemAllLocations(ctx context.Context, itemID uuid.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStockForItemAllLocations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockForItemSpecificLocation = `-- name: GetStockForItemSpecificLocation :many
SELECT id, item_id, location_id, quantity FROM stock
WHERE location_id = $1
`

func (q *Queries) GetStockForItemSpecificLocation(ctx context.Context, locationID uuid.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStockForItemSpecificLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveStock = `-- name: MoveStock :one
UPDATE stock
  SET quantity = quantity + $1
  WHERE item_id = $2 AND location_id = $3
RETURNING id, item_id, location_id, quantity
`

type MoveStockParams struct {
	Quantity   int32
	ItemID     uuid.UUID
	LocationID uuid.UUID
}

func (q *Queries) MoveStock(ctx context.Context, arg MoveStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, moveStock, arg.Quantity, arg.ItemID, arg.LocationID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.Quantity,
	)
	return i, err
}

const receiveStock = `-- name: ReceiveStock :one
INSERT INTO stock (
  item_id,
  location_id,
  quantity
) VALUES ($1, $2, $3)
ON CONFLICT (item_id, location_id)
DO UPDATE SET quantity = stock.quantity + EXCLUDED.quantity
RETURNING id, item_id, location_id, quantity
`

type ReceiveStockParams struct {
	ItemID     uuid.UUID
	LocationID uuid.UUID
	Quantity   int32
}

func (q *Queries) ReceiveStock(ctx context.Context, arg ReceiveStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, receiveStock, arg.ItemID, arg.LocationID, arg.Quantity)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.Quantity,
	)
	return i, err
}
