// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movements.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMovement = `-- name: CreateMovement :one
INSERT INTO stock_movements (item_id, from_location_id, to_location_id, quantity, moved_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_id, from_location_id, to_location_id, quantity, moved_by, moved_at
`

type CreateMovementParams struct {
	ItemID         uuid.UUID
	FromLocationID uuid.NullUUID
	ToLocationID   uuid.NullUUID
	Quantity       int32
	MovedBy        uuid.UUID
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) (StockMovement, error) {
	row := q.db.QueryRowContext(ctx, createMovement,
		arg.ItemID,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Quantity,
		arg.MovedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Quantity,
		&i.MovedBy,
		&i.MovedAt,
	)
	return i, err
}

const getAllMovements = `-- name: GetAllMovements :many
SELECT id, item_id, from_location_id, to_location_id, quantity, moved_by, moved_at FROM stock_movements
ORDER BY moved_at DESC
`

func (q *Queries) GetAllMovements(ctx context.Context) ([]StockMovement, error) {
	rows, err := q.db.QueryContext(ctx, getAllMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.MovedBy,
			&i.MovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovementsForItem = `-- name: GetMovementsForItem :many
SELECT id, item_id, from_location_id, to_location_id, quantity, moved_by, moved_at FROM stock_movements
WHERE item_id = $1
ORDER BY moved_at DESC
`

func (q *Queries) GetMovementsForItem(ctx context.Context, itemID uuid.UUID) ([]StockMovement, error) {
	rows, err := q.db.QueryContext(ctx, getMovementsForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.MovedBy,
			&i.MovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
