// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllStock = `-- name: GetAllStock :many
SELECT id, item_id, location_id, quantity FROM stock
ORDER BY location_id
`

func (q *Queries) GetAllStock(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getAllStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockForItemAllLocations = `-- name: GetStockForItemAllLocations :many
SELECT id, item_id, location_id, quantity FROM stock
WHERE item_id =
$1
`

func (q *Queries) GetStockForItemAllLocations(ctx context.Context, itemID uuid.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStockForItemAllLocations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockForItemSpecificLocation = `-- name: GetStockForItemSpecificLocation :many
SELECT id, item_id, location_id, quantity FROM stock
WHERE location_id = $1
`

func (q *Queries) GetStockForItemSpecificLocation(ctx context.Context, locationID uuid.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStockForItemSpecificLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.LocationID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveStock = `-- name: MoveStock :one
UPDATE stock
  SET quantity = quantity + $1
  WHERE item_id = $2 AND location_id = $3
RETURNING id, item_id, location_id, quantity
`

type MoveStockParams struct {
	Quantity   int32
	ItemID     uuid.UUID
	LocationID uuid.UUID
}

func (q *Queries) MoveStock(ctx context.Context, arg MoveStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, moveStock, arg.Quantity, arg.ItemID, arg.LocationID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.Quantity,
	)
	return i, err
}

const receiveStock = `-- name: ReceiveStock :one
INSERT INTO stock (
  item_id,
  location_id,
  quantity
) VALUES ($1, $2, $3)
ON CONFLICT (item_id, location_id)
DO UPDATE SET quantity = stock.quantity + EXCLUDED.quantity
RETURNING id, item_id, location_id, quantity
`

type ReceiveStockParams struct {
	ItemID     uuid.UUID
	LocationID uuid.UUID
	Quantity   int32
}

func (q *Queries) ReceiveStock(ctx context.Context, arg ReceiveStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, receiveStock, arg.ItemID, arg.LocationID, arg.Quantity)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.Quantity,
	)
	return i, err
}
